version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_curso
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflix
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./backups:/backups
    restart: always
    networks:
      - dbnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_curso
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    networks:
      - dbnet

  api:
    image: node:20
    container_name: api_netflix
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./:/app
    environment:
      PORT: 3000
      PGHOST: db          # <- host = nombre del servicio
      PGPORT: 5432
      PGDATABASE: netflix
      PGUSER: postgres
      PGPASSWORD: postgres
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - dbnet

volumes:
  pgdata:

networks:
  dbnet:
    driver: bridge
